### ISSUE TITLE
data preparation

### ISSUE THREAD

**Issue by mzarvandi** [ZifengDing/FITCARL#1]
Hello!
I am trying to run your model on my own dataset, and I'm having a hard time figuring out how you exactly generated the data files (from the main dataset files) you need to train your model. Could you please provide a script so that I can prepare the suitable data files for this repository from my own dataset?  

As far as I understood, one needs to generate following files to be able to use your model:
back_metrain.txt
back_metatest.txt
stat.txt
back_metavalid.txt
background_graph_for_rl.txt

**Comment by ZifengDing** [comment]
Hi!

Sorry I could not immediately find my script of this part. But I can tell you how to do it.
back_metatrain/back_metavalid/back_metatest are constructed by including all the quadruples from the background graph as well as the meta training/validation/test quadruples.
background_graph_for_rl.txt is just converting data format from FILT's data into text data.
Please refer to [this repo](https://github.com/Jasper-Wu/FILT) for more information.

**Comment by mzarvandi** [comment]
Thanks a lot!

Then can you also tell me how to prepare the other files the in processed_data folder? The following ones:

background_entities.pkl
ent2sec_matrix.npy
rel2secprob.pickle

meta_train_task_entity_to_quadruples_tohead.pickle
meta_valid_task_entity_to_quadruples_tohead.pickle
meta_test_task_entity_to_quadruples_tohead.pickle

meta_train_all_for_rl.txt
meta_valid_all_for_rl.txt
meta_test_all_for_rl.txt

meta_train_ent.pkl
meta_valid_ent.pkl
meta_test_ent.pkl



Also, the ones in the pretrain folder: In the paper you say you have generated them using the pretrained ComplEX. can you tell me how did you give your data to it (which files exactly), and what is this ComplEX pre-trained on?

**Comment by ZifengDing** [comment]
These files are made by FILT's author (Jasper Wu). Please open an issue at his repo (I posted in the last comment).
But I believe you can easily write a generation script yourself after you print these files out.
